name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: [ enhancement ]
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Describe the feature
      description: What should be added or improved?
      required: true